cloud-gov/shibboleth-boshrelease

- jobs/idp/templates/config/shibboleth/relying-party.xml
This adds the RelyingPartyOverrides and UnverifiedRelyingParty blocks to the relying-party configuration. They're purposefully left blank.
> Add blank properties

- README.md
- jobs/idp/templates/credentials/idp-encryption.crt.erb
- jobs/idp/templates/credentials/idp-encryption.key.erb
- jobs/idp/templates/credentials/idp-signing.crt.erb
- jobs/idp/templates/credentials/idp-signing.key.erb
> Metadata requires no BEGIN/END headers for keys and certs

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/authn/totp-authn-beans.xml.erb
- jobs/idp/templates/config/shibboleth/authn/totp-authn-config.xml.erb
This patch series adds the totp-authn-config file from the Totp plugin and pulls @jbarnicle's work from the plugin submodule.
> Add configurable totp-authn-config and bean

- jobs/idp/spec
- jobs/idp/templates/messages/authn-messages.properties.erb
@LinuxBozo @rogeruiz I'm not sure how to convert the `idp.authentication.failurePeriodSeconds` to minutes - I think we would maybe want that for the messaging?
> Templatize authn-messages to include lockout period in message

- jobs/idp/templates/messages/authn-messages.properties.erb
For the page at https://idp.fr.cloud.gov/profile/SAML2/POST/SSO?execution=e2s1, I believe that what we really want from people as a username is actually their email address, so I updated the string that seems to provide that info.
> Update "username" to "email address" in login UI

- jobs/idp/templates/config/tomcat/server.xml.erb
In order to reduce potential log messages which could contain sensitive information.[1][2]
1. https://tomcat.apache.org/tomcat-7.0-doc/security-howto.html
2. https://www.owasp.org/index.php/Securing_tomcat
> Turn off overly verbose stack traces

- src/tagish/src/main/java/com/tagish/auth/FileLogin.java
Before:
After (using inspect element):
> Username case sensitivity workaround

- jobs/idp/templates/credentials/idp-encryption.crt.erb
- jobs/idp/templates/credentials/idp-encryption.key.erb
- jobs/idp/templates/credentials/idp-signing.crt.erb
- jobs/idp/templates/credentials/idp-signing.key.erb
- jobs/idp/templates/metadata/idp-metadata.xml.erb
there's a disparity between certificates in use, some need to be PEM
format, and some need to be in DER format. this defaults to PEM format
wherever possible and then strips the headers where it needs to be DER
format.
None.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
> idp: update x509 rendering

- jobs/idp/templates/views/logout.vm.erb
- fix the syntax of the Velocity template for logging out. This will allow users to see a friendly logout message instead of a java stacktrace
None
> fix template syntax

- config/blobs.yml
Closes #77 
- Updates tomcat patch >7.0.104
> Update version, sha and object size for tomcat v7.0.105

- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
Prevent username enumeration by providing identical error messages regardless of whether it's a bad password or an unknown username.
- Update exception message
-
-
Addresses finding PT-01
> Address PT-01 and provide identical exceptions

- config/blobs.yml
- Update blob for tomcat to 7.0.108
Fix a POAM CG265-RA-5  for Tomcat CVEs
> updating tomcat to 7.0.108

- config/blobs.yml
- Upgrade shibboleth package from 3.2.1 to 3.4.8
Last updated 3.X release from vendor to resolve CAS issues
> moving shibboleth from 3.2.1 to 3.4.8

- .gitmodules
Updates the totp plugin submodule to the latest commit.
Updates the submodule url to the cloud-gov org in github instead of 18f.
None.
> update plugin to 3.4.8

- src/tagish/build.gradle
This copies the runtime jars to build/libs so the shibboleth bosh release package script will pick it up and copy it over. In our case, we only need the postgres driver.
This also tries the latest postgres driver.
uses the latest postgres driver.
> be sure to copy runtime jars

- jobs/idp/templates/config/tomcat/server.xml.erb
- Removes the JasperListener from the tomcat 8 server.xml as it is no longer used. This is causing on error on startup.
None
> JasperListener is no longer required

- config/blobs.yml
This changeset updates the OpenJDK release to use the latest version of Java 8.  Big thanks to @ChrisMcGowan for all of the help!
- Updates OpenJDK to Java 8 (8u302)
- This also added a new blob for the updated OpenJDK binary
- Helps us address recent security findings by keeping Java up-to-date
> Update OpenJDK to latest version of Java 8

- config/blobs.yml
This changeset updates the OpenJDK again to make sure it is running the latest release for the Java 1.8 series.
- Updates the OpenJDK to version 1.8-312b07
- Helps us address vulnerabilities and stay patched with the latest releases
> Update Java OpenJDK again

- config/blobs.yml
This changeset updates Apache Tomcat to address recent Nessus findings.
- Updates Tomcat to version 8.5.72
- Addresses recent Nessus findings with the older version of Tomcat that was running
> Update Tomcat to latest 8.5.x release

- config/blobs.yml
- bump tomcat
bigger version number == more secure software, probably
> bump tomcat

- jobs/idp/spec
- jobs/idp/templates/bin/pre-start
- jobs/idp/templates/helpers/ctl_setup.sh
- packages/idp/packaging
- packages/idp/spec
- packages/openjdk-11/spec.lock
- packages/openjdk-8/spec.lock
- Update to java 11
openjdk-11 is better-supported, so should have better response time if a CVE is discovered. Also, this is a requirement to update to idp4
> Update to java 11

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/authn/jaas.config
- jobs/idp/templates/config/shibboleth/authn/totp-authn-beans.xml.erb
- jobs/idp/templates/config/shibboleth/global.xml.erb
- templates/stub.yml
- Updated the code to use the testOnBorrow parameter to keep the connection searching during a disconnect
- Tested by creating a routing black hole for the RDS to force the idp to not respond, then delete the route and see that it does respond, simulating a database disconnect and connect. 
There are none, the code changed just looks for the database connection
> Add jdbc reconnect settings

- config/blobs.yml
- Update Tomcat to latest 9.x version
Addresses https://github.com/cloud-gov/private/issues/622
New versions of Tomcat include security patches and improvements.
> Update Tomcat to 9.0.71

- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
We have lately noticed an issue where users in UAA with multiple origins (e.g. the origin from this Shibboleth IdP and an origin for the agency SSO) start having login failures on this IdP origin once they have a second UAA account on the agency origin.
In the logs for the login failures was this error:
```
javax.security.auth.login.FailedLoginException: Invalid username or password at 
com.tagish.auth.DBLogin.validateUser(DBLogin.java:102)
```
The line of code ultimately pointed to this BOSH release. And upon further investigation, it seems like the `validateUser`  method from that line is running a manual SQL query against the UAA database to get the user's username/password information and to determine if the username/password during login was correct.
But when a user has two origins, …
> Update database login to handle users with multiple origins

- config/final.yml
- Set the host property to the fips endpoint
Instructs bosh to use the fips 140 compliant fips endpoint when interacting with S3.
> Fips endpoint

- config/blobs.yml
- update shibby to 4.3.3.
newer == more secure (maybe?)
> chore: update shibby to 4.3.3.

- config/blobs.yml
- Update Tomcat from 9.0.88 to 9.0.90
- Part of https://github.com/cloud-gov/private/issues/2031
-
Patching for CVEs
> Tomcat update.  Meow.
