cloud-gov/shibboleth-boshrelease

- templates/stub.yml
Adding the properties to the stub file for easier dev workflow.
> Add in the missing non-default properties

- jobs/idp/spec
Tied to the changes introduced in #14
> Clean up spec example for cert and keys

- jobs/idp/spec
> Add a colon because syntax

- jobs/idp/templates/config/shibboleth/authn/totp-authn-beans.xml.erb
> Update totp bean

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/authn/totp-authn-beans.xml.erb
- jobs/idp/templates/config/shibboleth/authn/totp-authn-config.xml.erb
> Update submodule to include latest plugin code

- jobs/idp/templates/config/shibboleth/authn/totp-authn-config.xml.erb
What I get for moving at the speed of :zap:
cc: @LinuxBozo
> Close template tags properly;

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/authn/jaas.config
- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
@LinuxBozo @rogeruiz  Going to do some local tests on the date logic to make sure it is accurate.
> add password expiration logic

- jobs/idp/templates/config/shibboleth/authn/jaas.config
- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
> remove extraneous semicolons

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/authn/jaas.config
- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
> add failed login functionality

- jobs/idp/spec
- jobs/idp/templates/config/shibboleth/global.xml.erb
- jobs/idp/templates/config/shibboleth/idp.properties
> Use JPA storage with postgres for HA

- jobs/idp/templates/config/shibboleth/global.xml.erb
> Fix jdbc url property for datasource

- jobs/idp/templates/config/shibboleth/global.xml.erb
> Update the datasource class

- jobs/idp/spec
- jobs/idp/templates/bin/pre-start
- jobs/idp/templates/messages/authn-messages.properties.erb
- jobs/idp/templates/views/error.vm.erb
- jobs/idp/templates/views/login.vm.erb
- jobs/idp/templates/views/logout.vm.erb
> Override login/logout views for customization

- config/blobs.yml
- packages/idp/packaging
- packages/idp/spec
> [WIP] Bump blobs to latest.

- packages/idp/packaging
> Fix tomcat tar path.

- config/blobs.yml
> Downgrade shibboleth to 3.2.1 pending more research on 3.3.0.

- src/tagish/src/main/java/com/tagish/auth/DBLogin.java
Should solve https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-9105 bug
> Make sure username is lowercased for all queries/logging

- jobs/idp/spec
- jobs/idp/templates/messages/authn-messages.properties.erb
- jobs/idp/templates/views/login.vm.erb
- jobs/idp/templates/views/logout.vm.erb
> Add help link on login/logout for resetting MFA

- config/blobs.yml
> Upgrade tomcat

- README.md
- jobs/idp/templates/metadata/idp-metadata.xml.erb
cleans up the release in prep for https://github.com/18F/cg-product/issues/1113. The `-` in the template rendering just deletes trailing newline characters.
None.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
> cleaned up docs and newlines.

- config/blobs.yml
- Bumped Tomcat version to make Peter happy
None
> Updated tomcat blobs to 7.0.104

- jobs/idp/templates/config/shibboleth/logback.xml
- add a logger and file appended for the totp plugin logs
None
> add logger and appender for totp plugin

- jobs/idp/spec
- packages/idp/packaging
- packages/idp/spec
- packages/openjdk-8/spec.lock
- vendor openjdk
also bumps to newer jdk, which is good
> vendor openjdk

- jobs/idp/templates/bin/pre-start
- jobs/idp/templates/helpers/ctl_setup.sh
- use openjdk script to find java
None
> use openjdk script to find java

- config/blobs.yml
- use tomcat 9
more versions, more better
> use tomcat 9

- config/blobs.yml
- jobs/idp/spec
- jobs/idp/templates/bin/pre-start
- packages/idp/packaging
- packages/idp/spec
- add shibboleth4 as an option
None
> add shibboleth4 as an option

- packages/idp/packaging
- create the directory before we use it
-
-
None
> create the directory before we use it

- jobs/idp/templates/bin/pre-start
> fix bash syntax

- jobs/idp/templates/bin/ctl
- jobs/idp/templates/config/shibboleth/global.xml.erb
- find cacerts better
- update storage class
-
none
> startup fixes

- config/blobs.yml
- jobs/idp/spec
- jobs/idp/templates/bin/pre-start
- jobs/idp/templates/config/shibboleth/attribute-resolver.xml.erb
- jobs/idp/templates/config/shibboleth/attributes/custom/mail.properties
- jobs/idp/templates/config/shibboleth/attributes/custom/uid.properties
- packages/idp/packaging
- add postgresql driver since it's no longer bundled
- update attribute-reference and friends for schema changes
None
> idp4 compatibility fixes

- jobs/idp/spec
> fix file path in spec file

- packages/idp/spec
- call out postgres in spec file
None
> call out postgres in spec file

- jobs/idp/templates/config/shibboleth/attribute-resolver.xml.erb
- jobs/idp/templates/config/shibboleth/global.xml.erb
- use correct property name
-
-
None
> use correct property name

- packages/idp/packaging
- copy totp and tagish libs to idp4 directories
None
> copy totp and tagish libs to idp4 directories

- jobs/idp/templates/bin/pre-start
- always define use_idp4
-
-
None
> always define use_idp4

- packages/idp/packaging
- copy tagish to idp3 and idp4 - idp3 was accidentally dropped when idp4 was added
None
> copy tagish to idp3 and idp4

- jobs/idp/templates/config/shibboleth/idp.properties
- add csrf to shibboleth
reduces chances of csrf attacks
> add csrf to shibboleth

- jobs/idp/templates/views/login.vm.erb
> add csrf to login view

- config/blobs.yml
- bump shibboleth to 4.2.1
None
> bump shibboleth to 4.2.1

- config/blobs.yml
> use tgz, not zip

- jobs/idp/spec
> default to using idp4

- config/blobs.yml
> Tomcat updates

- jobs/idp/templates/config/shibboleth/idp.properties
- Added googleapi for totp
- script for when totp is wrong
-
None
> csp improvements

- jobs/idp/templates/config/shibboleth/authn/totp-authn-beans.xml.erb
- modified the property for testOnBorrow to have the correct path
None as it is a change to one string that has no identifiable information.
> fixed typo in bean description for testOnBorrow

- jobs/idp/templates/config/shibboleth/idp.properties
- new version of QR thingy uses qrserver instead of google charts
-
-
None
> updated csp for qrserver

- src/tagish/build.gradle
- bump logging libraries for tagish, too
None
> chore: bump logging libraries for tagish, too
